const ActionTypes = {
    SET_PLAYERS: 'SET_PLAYERS',
    ADD_PLAYER_TO_TOURNEY: 'ADD_PLAYER_TO_TOURNEY',
    REMOVE_PLAYER_FROM_TOURNEY: 'REMOVE_PLAYER_FROM_TOURNEY',
    REMOVE_PLAYER: 'REMOVE_PLAYER',
    UPDATE_PLAYER: 'UPDATE_PLAYER',
    TOURNEY_FINISHED: 'TOURNEY_FINISHED',
    SET_ROOTGAME: 'SET_ROOTGAME',
    ADD_MATCH: 'ADD_MATCH',
    UPDATE_MATCH: 'UPDATE_MATCH',
    SET_MATCHES: 'SET_MATCHES',
    READY_TO_START: 'READY_TO_START',
    RESET_TOURNEY: 'RESET_TOURNEY',
    TOURNEY_STARTED: 'TOURNEY_STARTED',
    START_TOURNET: 'START_TOURNET'
};

export default ActionTypes;